version: '3.9'

services:
    database:
        image: postgres
        container_name: 'postgres_container'
        environment:
            POSTGRES_USER: /run/secrets/postgres_username
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB: sicooperative
        ports:
            - '5432:5432'
        volumes:
            - './.postgres:/var/lib/postgresql/data/'
        secrets:
            - postgres_password

secrets:
    postgres_username:
        file: .secrets/docker_postgres_username
    postgres_password:
        file: .secrets/docker_postgres_password