CREATE TABLE IF NOT EXISTS datalake.cartao (
    ID INTEGER PRIMARY KEY,
    NUM_CARTAO INT,
    NOM_IMPRESSO VARCHAR(100),
    ID_CONTA INTEGER REFERENCES datalake.conta (ID),
    ID_ASSOCIADO INTEGER REFERENCES datalake.associado (ID)
)