CREATE TABLE IF NOT EXISTS datalake.movimento (
    ID INTEGER PRIMARY KEY,
    VLR_TRANSACAO DECIMAL(10, 2),
    DES_TRANSACAO VARCHAR,
    DATA_MOVIMENTO TIMESTAMP,
    ID_CARTAO INTEGER REFERENCES datalake.cartao (ID)
)